global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'dvdtheque-main'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['127.0.0.1:8083']

  - job_name: 'allocine-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['127.0.0.1:8087']

  - job_name: 'tmdb-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['127.0.0.1:8086']
  
  - job_name: 'batch-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['127.0.0.1:8089']

  # les autres services (gateway, batch, etc.)